name: RecyclePlugin
main: com.svncho.RecyclePlugin
version: 2.0.0
api-version: '1.21'
author: svncho_
description: Fully configurable recycling system with GUI and XP rewards.

commands:

  recycle:
    description: Open the recycle GUI.
    usage: /recycle
    permission: recycleplugin.use

  rpadmin:
    description: RecyclePlugin admin command.
    usage: /rpadmin reload
    permission: recycleplugin.reload


permissions:

  recycleplugin.use:
    default: true

  recycleplugin.reload:
    default: op
    
  recycleplugin.update:
    default: op